inherit_from:
  - .rubocop_todo.yml

Layout/LineLength:
  Max: 120

Layout/ExtraSpacing:
  Enabled: true
  ForceEqualSignAlignment: false 

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: false #TODO: revisit later

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

